name: Manual Deploy to Coolify

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Coolify Redeployment with Authentication
        run: |
          curl -X POST "${{ secrets.COOLIFY_WEBHOOK_URL }}" \
          -H "Authorization: Bearer ${{ secrets.COOLIFY_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"force": true}'